### ISSUE TITLE
Reloading rightly annotated data failed

### ISSUE THREAD

**Issue by affection123456** [FLW-TUDO/3d_annotation_tool#9]
Hi. I got a problem when I reload the rightly annotated data. It do not stay at the position that I had put it at.

**Comment by AnasIbrahim** [comment]
Are you using the tool from this repo?
Please use the tool from the BOP toolkit https://github.com/thodan/bop_toolkit
Or for the latest stuff use my fork from https://github.com/AnasIbrahim/bop_toolkit but the code there is not release ready.

**Comment by affection123456** [comment]
Thanks very much for your reply! 

I use the tool from the BOP toolkit https://github.com/thodan/bop_toolkit    bop_toolkit/scripts/annotation_tool.py, but I still came across the same question mentioned before.

I also use your fork from  https://github.com/AnasIbrahim/bop_toolkit     bop_toolkit/scripts/annotation_tool/annotation_tool.py.
I came across the error below, while I don't have to manually create scene_gt.json in https://github.com/thodan/bop_toolkit.
`
File "prerelease_annotation_tool.py", line 832, in scene_load
    with open(scene_gt_path) as scene_gt_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/FoundationPose-data-res/Annotation/dataset/mbs/test/000000/scene_gt.json' `

Then I got a partly annotated scene_gt.json to the needed file path. After the annotated data is over, I came across the error before when I go next to a new image. 
`
Traceback (most recent call last):
  File "prerelease_annotation_tool.py", line 961, in <module>
    main()
  File "prerelease_annotation_tool.py", line 957, in main
    gui.Application.instance.run()
  File "prerelease_annotation_tool.py", line 918, in _on_next_image
    self.scene_load(self.scenes.scenes_path, self._annotation_scene.scene_num, self._annotation_scene.image_num + 1)
  File "prerelease_annotation_tool.py", line 834, in scene_load
    scene_data = data[str(image_num)]
KeyError: '6' `

**Comment by affection123456** [comment]
> Are you using the tool from this repo? Please use the tool from the BOP toolkit https://github.com/thodan/bop_toolkit Or for the latest stuff use my fork from https://github.com/AnasIbrahim/bop_toolkit but the code there is not release ready.

I add a "try-except" operation to the code below as the same in [https://github.com/thodan/bop_toolkit](url)  bop_toolkit/scripts/annotation_tool.py. Then the KeyError and FileNotFoundError still apear but got passed, the toolkit can work now and work very well.  Truly grateful for your support.

[https://github.com/AnasIbrahim/bop_toolkit](url)  bop_toolkit/scripts/annotation_tool/annotation_tool.py
line 793 - line 856
`
    try:
        self._scene.scene.add_geometry("annotation_scene", geometry, self.settings.scene_material,
                                       add_downsampled_copy_for_fast_rendering=True)
        # setting scene camera
        if p['tool_model'] == 'sequence':
            bounds = geometry.get_axis_aligned_bounding_box()
            self._scene.setup_camera(60, bounds, bounds.get_center())
            center = geometry.get_center()
            eye = center + np.array([-500, 0, 500])
            up = np.array([0, 0, 1])
            self._scene.look_at(center, eye, up)
        elif p['tool_model'] == 'individual':
            bounds = geometry.get_axis_aligned_bounding_box()
            self._scene.setup_camera(60, bounds, np.array([0, 0, 0]))
            eye = np.array([0, 0, 500])
            center = eye + np.array([0, 0, 2000])
            up = np.array([0, -1, 0])
            self._scene.look_at(center, eye, up)

        self._annotation_scene = AnnotationScene(geometry, scene_num, image_num)
        self._meshes_used.set_items([])  # clear list from last loaded scene

        # load values if an annotation already exists

        model_names = self.load_model_names()

        if p['tool_model'] == 'individual':
            scene_gt_file = 'scene_gt.json'
        elif p['tool_model'] == 'sequence':
            scene_gt_file = 'scene_gt_WORLD.json'
        scene_gt_path = os.path.join(self.scenes.scenes_path, f"{self._annotation_scene.scene_num:06}", scene_gt_file)
        # if os.path.exists(json_path):
        with open(scene_gt_path) as scene_gt_file:
            data = json.load(scene_gt_file)
            scene_data = data[str(image_num)]
            active_meshes = list()
            obj_meshes_colored = []
            for obj in scene_data:  # add object to annotation_scene object
                # load object mesh
                obj_mesh_path = os.path.join(self.scenes.objects_path, 'obj_' + f"{int(obj['obj_id']):06}" + '.ply')
                # assert normals exist
                #assert not obj_geometry.has_normals(), "Object mesh does not have normals. Exiting ..."

                obj_geometry, obj_mesh_colored = self._load_object(obj_mesh_path)

                obj_meshes_colored.append(obj_mesh_colored)

                #obj_geometry.points = o3d.utility.Vector3dVector(np.array(obj_geometry.points))  # object point cloud in mm
                model_name = model_names[int(obj['obj_id']) - 1]
                obj_instance = self._obj_instance_count(model_name, active_meshes)
                obj_name = model_name + '_' + str(obj_instance)
                translation = np.array(np.array(obj['cam_t_m2c']), dtype=np.float64)  # distance in mm
                orientation = np.array(np.array(obj['cam_R_m2c']), dtype=np.float64)
                transform = np.concatenate((orientation.reshape((3, 3)), translation.reshape(3, 1)), axis=1)
                transform_cam_to_obj = np.concatenate(
                    (transform, np.array([0, 0, 0, 1]).reshape(1, 4)))  # homogeneous transform

                self._annotation_scene.add_obj(obj_geometry, obj_name, obj_instance, transform_cam_to_obj)
                # adding object to the scene
                obj_geometry.transform(transform_cam_to_obj)
                self._scene.scene.add_geometry(obj_name, obj_geometry, self.settings.annotation_obj_material,
                                               add_downsampled_copy_for_fast_rendering=True)
                active_meshes.append(obj_name)
            self._obj_meshes_colored = all(obj_meshes_colored)  # this is used to determione which ICP to use (colored ir PointToPoint)
        self._meshes_used.set_items(active_meshes)
    except Exception as e:
            print(e)
`

**Comment by affection123456** [comment]
> Are you using the tool from this repo? Please use the tool from the BOP toolkit https://github.com/thodan/bop_toolkit Or for the latest stuff use my fork from https://github.com/AnasIbrahim/bop_toolkit but the code there is not release ready.

I add a "try-except" operation to the code below as the same in [https://github.com/thodan/bop_toolkit](url)  bop_toolkit/scripts/annotation_tool.py. Then the KeyError and FileNotFoundError still apear but got passed, the toolkit can work now and work very well.  Truly grateful for your support.

[https://github.com/AnasIbrahim/bop_toolkit](url)  bop_toolkit/scripts/annotation_tool/annotation_tool.py
line 793 - line 856

```python
try:
    self._scene.scene.add_geometry("annotation_scene", geometry, self.settings.scene_material,
                                   add_downsampled_copy_for_fast_rendering=True)
    # setting scene camera
    if p['tool_model'] == 'sequence':
        bounds = geometry.get_axis_aligned_bounding_box()
        self._scene.setup_camera(60, bounds, bounds.get_center())
        center = geometry.get_center()
        eye = center + np.array([-500, 0, 500])
        up = np.array([0, 0, 1])
        self._scene.look_at(center, eye, up)
    elif p['tool_model'] == 'individual':
        bounds = geometry.get_axis_aligned_bounding_box()
        self._scene.setup_camera(60, bounds, np.array([0, 0, 0]))
        eye = np.array([0, 0, 500])
        center = eye + np.array([0, 0, 2000])
        up = np.array([0, -1, 0])
        self._scene.look_at(center, eye, up)
    self._annotation_scene = AnnotationScene(geometry, scene_num, image_num)
    self._meshes_used.set_items([])  # clear list from last loaded scene
    model_names = self.load_model_names()

    if p['tool_model'] == 'individual':
        scene_gt_file = 'scene_gt.json'
    elif p['tool_model'] == 'sequence':
        scene_gt_file = 'scene_gt_WORLD.json'
    scene_gt_path = os.path.join(self.scenes.scenes_path, f"{self._annotation_scene.scene_num:06}", scene_gt_file)
    # if os.path.exists(json_path):
    with open(scene_gt_path) as scene_gt_file:
        data = json.load(scene_gt_file)
        scene_data = data[str(image_num)]
        active_meshes = list()
        obj_meshes_colored = []
        for obj in scene_data:  # add object to annotation_scene object
            # load object mesh
            obj_mesh_path = os.path.join(self.scenes.objects_path, 'obj_' + f"{int(obj['obj_id']):06}" + '.ply')
            # assert normals exist
            # assert not obj_geometry.has_normals(), "Object mesh does not have normals. Exiting ..."

            obj_geometry, obj_mesh_colored = self._load_object(obj_mesh_path)

            obj_meshes_colored.append(obj_mesh_colored)

            # obj_geometry.points = o3d.utility.Vector3dVector(np.array(obj_geometry.points))  # object point cloud in mm
            model_name = model_names[int(obj['obj_id']) - 1]
            obj_instance = self._obj_instance_count(model_name, active_meshes)
            obj_name = model_name + '_' + str(obj_instance)
            translation = np.array(np.array(obj['cam_t_m2c']), dtype=np.float64)  # distance in mm
            orientation = np.array(np.array(obj['cam_R_m2c']), dtype=np.float64)
            transform = np.concatenate((orientation.reshape((3, 3)), translation.reshape(3, 1)), axis=1)
            transform_cam_to_obj = np.concatenate(
                (transform, np.array([0, 0, 0, 1]).reshape(1, 4)))  # homogeneous transform

            self._annotation_scene.add_obj(obj_geometry, obj_name, obj_instance, transform_cam_to_obj)
            # adding object to the scene
            obj_geometry.transform(transform_cam_to_obj)
            self._scene.scene.add_geometry(obj_name, obj_geometry, self.settings.annotation_obj_material,
                                           add_downsampled_copy_for_fast_rendering=True)
            active_meshes.append(obj_name)
        self._obj_meshes_colored = all(obj_meshes_colored)  # this is used to determine which ICP to use (colored or PointToPoint)
    self._meshes_used.set_items(active_meshes)
except Exception as e:
        print(e)
```
